return {
  -- -- Neotest Adapters
  -- { "nvim-neotest/neotest-plenary" },
  -- { "nvim-neotest/neotest-jest" },
  -- { "marilari88/neotest-vitest" },
  -- { "thenbe/neotest-playwright" },
  -- -- { "andy-bell101/neotest-java" },
  --
  -- -- Neotest
  -- {
  --   "nvim-neotest/neotest",
  --   opts = {
  --     adapters = {
  --       "neotest-plenary",
  --       "neotest-jest",
  --       "neotest-vitest",
  --       -- "neotest-java",
  --       "neotest-playwright",
  --     },
  --   },
  -- },
}
