#!/bin/bash
source "$HOME"/.local/share/chezmoi/dot_config/scripts/spinner.sh

echo "Installing packages"
brew bundle --file=/dev/stdin >"$HOME"/install-packages.log <<EOF
brew "bat"
brew "bottom"
brew "brotli"
brew "chezmoi"
brew "cmake"
brew "fd"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-flow"
brew "git-lfs"
brew "git-delta"
brew "go"
brew "jp"
brew "jq"
brew "lazygit"
brew "localstack"
brew "lsd"
brew "lua"
brew "luajit"
brew "luarocks"
brew "luv"
brew "make"
brew "mysql"
brew "neovim"
brew "nvm"
brew "oh-my-posh"
brew "oven-sh/bun/bun"
brew "openssl"
brew "packer"
brew "perl"
brew "pycparser"
brew "pyenv"
brew "certifi"
brew "cryptography"
brew "python-setuptools"
brew "python"
brew "ripgrep"
brew "rustup"
brew "sqlite"
brew "terraform"
brew "unzip"
brew "yq"
brew "zellij"
brew "zoxide"
brew "zsh"
brew "zsh-autocomplete"
brew "zsh-completions"
brew "zstd"
cask "alacritty"
cask "orbstack"
cask "jetbrains-toolbox"
cask "ghostty"
cask "cursor"
cask "visual-studio-code"
EOF

echo "Environment setup complete. (logs in $HOME/install-packages.log)"
echo "Please run 'source ~/.zshrc' to apply changes."
