import = ["~/.config/alacritty/dracula.toml"]

[font]
size = 14.0
[font.normal]
family = "MonoLisa"
style = "Light"
[font.bold]
family = "MonoLisa"
style = "Bold"
[font.italic]
family = "MonoLisa"
style = "Light Italic"
[font.bold_italic]
family = "MonoLisa"
style = "Bold Italic"

# [cursor]
# vi_mode_style = { shape = "Block", blinking = "Always"}

[window]
padding.x = 10
padding.y = 10
decorations = "none"

[scrolling]
multiplier = 1

[env]
TERM = "xterm-256color"
